OoliteProject/oolite

src/Core/HeadUpDisplay.m

This fixes the target reticle positionning issue in all 4 views + custom.

Target reticle positionning now takes the field of view into account.

---

src/Cocoa/MyOpenGLView.m

This is an attempt to fix issue 136.  There are two possible fixes, selected by setting the `issue_136_fix` user default to `0` (off), `1` (first fix) or `2` (second fix).
As I can't test whether the code builds, I'd appreciate somebody else at least looking over it before merging to master.

Attempt to fix scissor test failure (issue 136)

---

README.txt
src/Core/Materials/OOPNGTextureLoader.m
src/Core/MiniZip/ioapi.h

Fix for issue 139, the compilation failure on Gentoo.  Also tested on Debian.

Fix compilation on Gentoo

---

src/Core/OOMesh.m

This is just the lighting fix from #146, enabled by setting the lighting-fix-tentative user default to YES.

Add fix for lighting bug, enabled by lighting-fix-tentative user default

---

src/Cocoa/MyOpenGLView.m
src/Core/Entities/PlayerEntity.m
src/Core/Scripting/OOJSInterfaceDefinition.m
src/Core/Scripting/OOJSPopulatorDefinition.m

Fix the project to build under Xcode 7.

---

src/Core/OOCocoa.h

Fix Travis builds

---

src/Core/Scripting/OOJSPlayerShip.m

Open to suggestions here. I believe this code works as intended, but there may be an easier way of doing this than what I've implemented here. I was trying to avoid having to re-write all the compass mode code into a new function, and this seemed like the simplest way to achieve that. Let me know what you think.

making playership.compassTarget readwrite

---

src/Cocoa/MyOpenGLView.h
src/Cocoa/MyOpenGLView.m
src/Core/GameController.m

This implementation is pretty much identical to the SDL side.
http://www.aegidian.org/bb/viewtopic.php?f=6&t=18927

Implements mouse wheel for Mac

---

src/Core/Scripting/OOJSGlobal.m

Suggestion by Commander Astrobe to be able to pause the game from script
http://www.aegidian.org/bb/viewtopic.php?f=6&t=18900

Scripting: adds 'pauseGame()' method to pause the game from script

---

src/Core/Entities/ShipEntity.m
src/Core/Scripting/OOJSPlayerShip.m

In a discussion about the reverse-control behavior, it was suggested that pitch/roll/yaw for playership be writable. 
http://www.aegidian.org/bb/viewtopic.php?f=6&t=9142

Scripting: Makes pitch/roll/yaw for playerShip writable

---

src/Core/GuiDisplayGen.h
src/Core/GuiDisplayGen.m
src/Core/Scripting/OOJSGlobal.m
src/Core/Universe.m

I haven't added functions for all the different value types in "gui-settings.plist" - just the color ones for the moment. And I'm not sure about my method of checking if the setting key is color-related. There might be a better way of doing this.

Edit gui color settings in gui-settings.plist

---

Resources/Shaders/oolite-default-atmosphere.fragment

This is a new atmosphere shader which uses a Fresnel torus around the planet to produce the effect. Overall it looks better than what we had till now.
Performance seems unchanged according to initial tests and some simplifications have been made in the shader to reduce the amount of calculations done. The fade in and out effect at large distances has been removed because it no longer seems necessary. 
I intend to merge this very soon, so if there are any comments or objections, about now would be a good time to be put forward. :-)

New atmosphere shader

---

src/Core/Entities/PlayerEntityContracts.m
src/Core/Entities/PlayerEntityControls.m
src/Core/Scripting/OOJSStation.m

This is so a laser weapon can be included in "extras" array and added to the ship.

addShipToShipyard look for and add lasers from extras array

---

src/Core/Entities/Entity.h
src/Core/Entities/Entity.m
src/Core/Scripting/OOJSEntity.m

Allowing scripts to determine if entity is in shadow or not

Adding 'IsSunlit' to entity

---

src/Core/Scripting/OOJSPlayerShip.m

To allow scripts to know which of the missiles is currently selected

Adding activeMissile property

---

Resources/Scripts/oolite-populator.js

equipmentKey should be used instead

Missiles in ship missiles array do not have a primary role

---

src/Core/GuiDisplayGen.m

Increasing opacity of cursor for increased visibility

---

Resources/Scripts/oolite-equipment-control.js

Regardless of the order of loading

Ensure any equipment incompatibility refs are enforced

---

Resources/Scripts/oolite-equipment-control.js

And added a variable declaration

Added check to avoid null values in equipmentInfo items

---

src/Core/Entities/DockEntity.m
src/Core/Entities/Entity.h
src/Core/Entities/Entity.m
src/Core/Entities/OOPlasmaShotEntity.m
src/Core/Entities/OOQuiriumCascadeEntity.m
src/Core/Entities/PlayerEntity.m
src/Core/Entities/PlayerEntityControls.m
src/Core/Entities/PlayerEntityLegacyScriptEngine.m
src/Core/Entities/PlayerEntitySound.h
src/Core/Entities/PlayerEntitySound.m
src/Core/Entities/ShipEntity.h
src/Core/Entities/ShipEntity.m
src/Core/Entities/StationEntity.m
src/Core/OOEquipmentType.h
src/Core/OOEquipmentType.m
src/Core/Scripting/OOJSShip.m

This PR adds the ability to link custom sounds to particular lasers, missiles and mines. The purpose here was to make a high-powered weapon sound different to a low-powered one, and for a laser hit to sound different to a missile hit. The following keys are now available in the "weapon_info" dictionary of an equipment definition. Each of the "fx_*" keys is a reference to a key entry in the customsounds.plist file.
fx_shot_miss_name		Played when weapon is fired but does not hit anything (laser weapons only).
fx_shot_hit_name		Played when weapon is fired and hits another ship (laser weapons only).
fx_hitplayer_shielded_name	Played when weapon hits the player ship while shields are up.
fx_hitplayer_unshielded_name	Played when weapon hits the player ship while shields are down. …

Adding ability to use custom sounds for specific lasers

---

src/Core/Entities/PlayerEntity.m

Add message to exit pause, when paused in flight and Game Load/Save screen is active.

Add game paused message in Game Options when in flight.

---

README.md

It took me quite some time to compile on Fedora Linux, so I thought it might be a good idea to add all the information needed to do this to the README.md.

Better organized README.md for compiling on Linux

---

README.md

Updated README.md with Ubuntu compilation instructions

---

Resources/Scripts/oolite-populator.js
Resources/Scripts/oolite-priorityai.js

A couple of protections against null/missing values, and a fix for pre-1.84 market properties.

Small tweaks and bugfixes for some javascript functions

---

Resources/Scripts/oolite-priorityai.js

And let's not talk about my complete brain fade ever again.

Correction to logic for homeSystem function in priorityai

---

src/Core/Entities/PlayerEntityKeyMapper.m

Trying to limit ways of entering invalid key combinations.

Auto-switches the case on keys when shift is changed manually

---

src/Core/Entities/PlayerEntityControls.m

allowing snapshot on long range chart

---

Doc/CHANGELOG.TXT
src/Core/Universe.m

And updates some changelog entries.

Adds consoleMessageReceived event

---

Doc/CHANGELOG.TXT
Resources/Config/missiontext.plist
Resources/Scripts/oolite-tutorial.js

We've had a couple of players get inside the dock and then stop, rotating in place and waiting. This tip encourages them to keep moving forward, towards the rear of the docking bay.

Adds extra docking tip, reminding players to keep moving forward

---

src/Core/Entities/PlayerEntityKeyMapper.m

This was a display issue only - the keyboard layout was correctly saved, it just wasn't reflected on the page.

Fixes issue where current keyboard layout was not showing in list
