src/Core/Entities/PlayerEntity.m
src/Core/Universe.m

Fix for issue mentioned on the mailing list where the planet in the system info screen was being rendered at unusual sizes when the window has odd aspect ratios.  Obviously, this can be delayed until after 1.82 release.

Gui planets

---

src/Core/Entities/PlayerEntity.h
src/Core/Entities/PlayerEntity.m
src/Core/Entities/PlayerEntityControls.m
src/Core/Entities/ShipEntity.h
src/Core/Entities/ShipEntity.m
src/Core/OOCollectionExtractors.m
src/Core/OOVector.h
src/Core/OOVector.m
src/Core/Scripting/OOJSShip.m
src/Core/Scripting/OOJSVector.h
src/Core/Scripting/OOJSVector.m
src/Core/Scripting/OOJavaScriptEngine.m
src/Core/Universe.m

This is a rewrite of the laser mount code to allow multiple mount points to be fitted on a single direction in a nicer way than the "subentity" pattern, including fitting multiple lasers on aft or side mounts, and including player ships.
`weapon_mount_mode` is a new shipdata property which can be "single", "split" or "multiply". "single"is the default value and duplicates 1.82 behaviour for backward compatibility. The other two change the expected value of `weapon_position_forward` (and the other three) from a vector expression to an array of vector expressions. "split" then splits the damage from the weapon across those positions - it's cosmetic only, so long as you hit with all of them; "multiply" is (mostly) equivalent to doing it with subentities in that each beam is a full power shot …

Multiple laser mounts

---

Resources/Config/logcontrol.plist
src/Core/Entities/OOEntityWithDrawable.h
src/Core/Entities/OOExhaustPlumeEntity.m
src/Core/Entities/OOFlasherEntity.m
src/Core/Entities/OOVisualEffectEntity.m
src/Core/Entities/ShipEntity.m
src/Core/OOCacheManager.m
src/Core/OOMesh.h
src/Core/OOMesh.m
src/Core/Universe.m

This is the proposed resolution for the cache issues related to rescaling models (#176). Given that the cache is a high-risk area, I'd rather give a chance for the proposal to be reviewed first, rather than merging staight away.
As per this PR, separate entries are now inserted in the cache for models of different scale factors, applying both to mesh and octree data. Before this patch, octree data was entered in the cache for only one scale factor and subsequent calls for creation at other scale factors would result in a model that had collision detection and volume calculation issues. This could have very well been the cause of some weird bugs reported rarely in the past, whereby a player ship would be apparently hit by "something" and get ejected at excessive velocities towards a random …

Proposed fix for issue #176 (Cache problems with rescaled models).

---

Doc/contributors.txt
Resources/Config/material-defaults.plist
Resources/Shaders/oolite-default-atmosphere.fragment
Resources/Shaders/oolite-default-atmosphere.vertex
src/Core/Entities/OOPlanetEntity.m

As already mentioned in the internal devs mailing list, this is a request to merge Commander_X's new atmosphere shader to master.
The effect looks good and, on my system, offers about 10 FPS more than the atmosphere implementation we have now. The effect fades out when the atmosphere is entered or we move too far away from the planet. The effect's fade in/out distance as well as the fade in/out rate are planet radius dependent. The old effect is still applied on detail levels below Extra Detail.
The shader can still use some optimizations but I think that it is now at a state where it can be imported to trunk and tested by a wider user base.

Shady atmos alternative

---

src/Core/Entities/OOPlanetEntity.h
src/Core/Entities/OOPlanetEntity.m

With the recent implementation of shader atmospheres, it became evident that the cloud effect (an internally generated texture) had to go, as the implementation was giving us only two options: either shader or texture atmosphere. The design also predicted that, if the shader atmosphere could not be generated for whatever reason, then there was an automatic fall-back to the texture  generated one.
This PR enables both atmosphere types to co-exist and I believe the visual result is worth it. The implementation is relatively simple and relies on two atmosphere drawables being defined per planet. One is for a texture and the other is for a shader effect. The design tries to keep as close as possible to the earlier one. Now, a texture atmosphere is always generated, like in 1.84. The shader …

Support for shader + texture atmosphere drawables simultaneously

---

src/Core/Entities/OOPlanetEntity.m
src/Core/Materials/OOPlanetTextureGenerator.h
src/Core/Materials/OOPlanetTextureGenerator.m
src/Core/Materials/OOStandaloneAtmosphereGenerator.h
src/Core/Materials/OOStandaloneAtmosphereGenerator.m

Rather than setting Perlin3D planet and atmosphere textures perference at compile time, I thought that it could be a better idea if we could have this selection as an option. This could motivate also contributors to try to optimize the Perlin3D code, too.
This pull request implements this idea. The type of texture for planets and atmospheres can be set via the "perlin_3d" key in planetinfo.plist for each planet separately or for everything, if set inside the "universal" block. 
By default we keep Perlin3D disabled due to its performance impact. There is an approximately two seconds delay on my system when viewing planets in the F7 screen with this enabled. Hyperspace transit takes somewhat longer too, as the new system textures get created. However, more powerful systems could maybe use …

Perlin3D Planet and Atmosphere Textures as planetinfo.plist Option

---

Resources/Config/descriptions.plist
src/Core/Entities/PlayerEntity.m

Opens the layout of the information on the F7 screen so that OXP's can potentially add their own information in the top part of the screen.
Also, I've created an OXP to add a control layer to the layout, which can be found here: [SystemDataConfig_0.3.zip](https://app.box.com/s/zl24eisa5orvrrsskzbh5q137rijs887)

F7 screen config and layout

---

src/Core/Entities/ShipEntity.h
src/Core/Entities/ShipEntity.m
src/Core/Scripting/OOJSShip.m

This adds the "addCargoEntity" to the player ship, allowing cargo entities to be added directly to the players cargo hold. 1 required param (the actual cargo entity, which must be a valid cargo entity currently in space somewhere), 2 optional params: processEvents (bool, default false) to indicate whether normal scooping events (eg shipScoopedOther) should be executed; processMessages (bool, default false) to indicate whether normal scooping messages (eg "You rescued Bill Gates")  should be displayed.

Adding 'addCargoEntity' method to player ship

---

src/Core/Entities/PlayerEntity.h
src/Core/Entities/PlayerEntity.m
src/Core/Scripting/OOJSPlayerShip.m

This update hopefully provides the events and methods that will allow OXP devs to automatically prime a piece of equipment whenever an MFD is selected or changed by the player. There are two new events (selectedMFDChanged and mfdKeyChanged) and one new method (player.ship.setPrimedEquipment).

Adds events and controls for MFDs and primed equipment

---

src/Core/Debug/OODebugTCPConsoleClient.m
src/Core/Entities/OOSunEntity.m
src/Core/Entities/PlayerEntityLoadSave.m
src/Core/Entities/ShipEntity.m
src/Core/Materials/OOShaderProgram.m
src/Core/OOCache.m
src/Core/OOConvertSystemDescriptions.m
src/Core/OOOpenGL.m
src/Core/OOStringExpander.m
src/Core/OXPVerifier/OOCheckDemoShipsPListVerifierStage.m
src/Core/OXPVerifier/OOCheckEquipmentPListVerifierStage.m
src/Core/OXPVerifier/OOCheckRequiresPListVerifierStage.m
src/Core/OXPVerifier/OOCheckShipDataPListVerifierStage.m
src/Core/OXPVerifier/OOFileScannerVerifierStage.m
src/Core/OXPVerifier/OOModelVerifierStage.m
src/Core/OXPVerifier/OOOXPVerifier.m
src/Core/OXPVerifier/OOPListSchemaVerifier.m
src/Core/Octree.m
src/Core/ResourceManager.m
src/Core/Scripting/OOJSEngineTimeManagement.m
src/Core/Universe.m
src/SDL/MyOpenGLView.m

I've just switch distros on my laptop, and ran into a couple of compilation problems.  The main one is an issue that's happened before - if there's a line such as 
```
OOLog(@"category", @"message");
```
the compile fails because a modern GNUstep release includes a `-Werror=format-security` switch which insists that you replace the line with something like
```
OOLog(@"category", @"%@", @"message");
```
This is more secure if there's a possibility that the @"message" string is user provided. None of ours are, but the damn thing is going to keep complaining until we give in and fix it, so that's what this pull request does. It is possible to fix this temporarily by editing `GNUstep/Makefiles/config.make` and changing the switch to `-Wformat-security`, but every time there's a GNUstep update …

Gnustep complaints

---

src/Cocoa/MyOpenGLView.m

This recenters the virtual joystick and warps the mouse cursor to the center of the screen, in order to have the same functionality as its SDL equivalent resetMouse method.

Implements MyOpenGLView::resetMouse for Mac

---

src/Core/GuiDisplayGen.m

This completes the code that was already in place to prevent unnecessary recalculation of routes.

Prevents recalculating route every frame on Chart view

---

Doc/LICENSE.TXT

Copyright line in license says 2004-2011.
Changed 2011 into 2017 as that is the current year

Bumps Copyright year to 2017

---

src/Core/Entities/ShipEntity.m

This is really nothing, but it breaks the function dropdown menu in the xcode IDE.

Unbalanced braces break function dropdown in xcode IDE

---

Doc/FAQ.TXT

The FAQ in the documentation was referencing a non-existent file PLAYING.TXT to provide controller information specific to the Oolite project. This file is not present in the repository and so we can instead link to the Wiki.
Closes #319

Change FAQ reference from PLAYING.TXT to controller wiki

---

src/SDL/MyOpenGLView.m

Trying to find a fix for the color banding issue that we see sometimes on planets on any graphics card that does not do dithering. Seems to work well on Windows, Linux needs some more testing but it seems to work too.
The solution is to request OpenGL to set up a 16 bits per color component buffer on stasrtup. However, since there has been one report of 100% usage on the video card (not reproducible at this time), we set the 16bpcc only as an option, if the user requests it. The option can be toggled from both the command line and the defaults file.

16 bits per color component as startup parameter

---

src/Core/Entities/PlayerEntity.h
src/Core/Entities/PlayerEntity.m
src/Core/Entities/PlayerEntityContracts.m
src/Core/Entities/StationEntity.h
src/Core/Entities/StationEntity.m
src/Core/Scripting/OOJSStation.m
src/Core/Universe.h

Adds station.shipyard property to station to view current ships in shipyard.
Adds station.addShipToShipyard to add new ship to shipyard
Adds station.removeShipFromShipyard to remove a ship from the shipyard.
eg of adding ship:
```
var def = {
short_description:"A sample ship to demonstrate adding a ship to the shipyard",
shipdata_key:"cobra1_player_able",
price:120000,
personality:Math.floor(Math.random() * 32768),
extras:["EQ_FUEL_INJECTION","EQ_GAL_DRIVE"]
};
player.ship.dockedStation.addShipToShipyard(def);
```
eg of removing ship
`   player.ship.dockedStation.removeShipFromShipyard(1); // removes ship at index position 1`

Provides JS access to the shipyard of a station

---

src/Core/Scripting/OOJSStation.m

(2nd try)
`station.shipyard` was incorrectly creating shipyard entries even when `hasShipyard` was false.

station.shipyard generates shipyard when hasShipyard is false

---

src/Core/Entities/PlayerEntityContracts.h
src/Core/Entities/PlayerEntityContracts.m
src/Core/Scripting/OOJSPlayer.m

Gives OXP's an opportunity to do something before the player ship is actually sold/replaced.
Event is in two forms: 
1. When player actually buys a ship from the F3F3 shipyard.
`this.playerWillBuyNewShip = function(shipKey, shipyard_info, price, tradeIn) {  }`
2. When player ship is changed via the JS method player.replaceShip("shipkey")
`this.playerWillBuyNewShip = function(shipKey) {  }`

Adding playerWillBuyNewShip world event

---

src/Core/OOProbabilisticTextureManager.h
src/Core/OOProbabilisticTextureManager.m
src/Core/ResourceManager.h
src/Core/ResourceManager.m

This adds the ability to limit star and nebula textures to particular galaxies, providing the opportunity to make galaxies more visually unique. 
At the same time, in order to make the merging of star and nebula textures more logical and consistent, they are now being merged on the "texture" key. Therefore, if an OXP overrides the "oolite-nebula-1.png" definition in a "nebulatextures.plist" file (for instance, adding a galaxy or changing the probability), they can be confident this change has been applied. To allow for the same texture to appear in multiple galaxies, an optional "key" property can be added to the dictionary, which will take the place of the "texture" property when merging the arrays.
To demonstrate this, use the following in place of the current nebulatextures.plist, …

Limiting star and nebula textures by galaxy

---

src/Core/ResourceManager.h
src/Core/ResourceManager.m

Adds the ability to process equipment-overrides.plist files, which allows OXP authors to more easily update existing equipment items without needing to copy the entire equipment.plist entry in order to do so. Also, it reduces the potential conflicts where two OXP's want to update the same equipment item. It doesn't solve the issue of two OXP's wanting to update the same properties of said equipment item - the last overrides file will still be the winner here, which is the same for the shipdata-overrides file.
The format of the equipment-overrides.plist is slightly different to the equipment.plist file by necessity. A sample file is shown:
```
{
"EQ_WEAPON_PULSE_LASER" = {
techlevel = 7;
price = 50000;
short_description = "Laser Pointer";
long_description = "A simple, all purpose (but …
```

Adding support for equipment-overrides.plist

---

src/Core/OOEquipmentType.h
src/Core/OOEquipmentType.m
src/Core/Scripting/OOJSEquipmentInfo.m

weapon_info was included in equipment.plist in v1.81, but there's no way for scripts to recover that information, so I added it to EquipmentInfo scripting object as 'weaponInfo', a dictionary with the weapon_info fields from equipment.plist (used scripInfo as template)
I have been using this mod for 9 days (Towbar v0.105 's Laser Reductor uses it to set the amount of energy to give back when a derelicts is hit), the glitches were all on the script side.
There are a few other OXPs that use weapon_info, but they are expecting a dictionary with name "weapon_info"... the property I added is camel case, like all other scripting object's properties, so those OXPs will have to be updated to use the new property

Adds weaponInfo to EquipmentInfo script object

---

src/SDL/MyOpenGLView.m

On Fedora 32, gcc 10.2.1 reports an error:
```bash
Compiling file src/SDL/MyOpenGLView.m ...
src/SDL/MyOpenGLView.m: In function ‘-[MyOpenGLView init]’:
src/SDL/MyOpenGLView.m:327:2: error: format not a string literal and no format arguments [-Werror=format-security]
327 |  OOLog(@"display.initGL", @"Achieved color / depth buffer sizes (bits):");
|  ^
cc1obj: some warnings being treated as errors
```
This PR fixes the issue on my system.

Fix an error reported by gcc about format-security

---

README.md
src/Core/OOShipRegistry.h
src/Core/OOShipRegistry.m
src/Core/Scripting/OOJSShip.m

This should add the javascript function `function setShipDataForKey(datakey : String, newShipData : Object)` that sets the shipdata for a specific datakey. This will allow OXPs to fiddle with the properties of all ships directly. For example, an OXP that sets the `shipdata.max_yaw` value to 60% that of `shipdata.max_pitch`, emulating a similar mechanic in Elite: Dangerous, where the maximum yaw is smaller than the pitch. Or an OXP that re-evaluates the prices of ships in the shipyard.
I also added some helpful tips for compiling on Linux.
This is a draft because I am not sure, if I introduced memory leaks, as I don't know Objective-C very well.

Adding "setShipInfoForKey"

---

src/Core/Scripting/OOJSShip.m

Adding a weapon to the player ship via a script passes a "purchase" context through to the "allowAwardEquipment" condition script call, even when the weapon is added via script. This code change enforces the "scripted" context when a weapon change is made by script.

Fix for correct context when adding weapons to player ship

---

src/Core/Entities/PlayerEntity.m

Fixes issue #400, by allowing to customize the time limit of startUp scripts in the `oolite.plist` config file. Defaults to previous value of 5 seconds.

Added option for startUp script time limit

---

Resources/Config/descriptions.plist
Resources/Config/missiontext.plist

The goal here is to make the fast activation screen clearer, so the player doesn't have to know what key is associated with "fast activate defense" and "fast activate offense".

Adjusts descriptions on fast activation pages for better clarity

---

GNUmakefile
src/SDL/MyOpenGLView.h
src/SDL/MyOpenGLView.m

The main feature this PR implements is HDR display device detection capability on Windows. If -hdr has been passed as startup parameter, we now check whether the primary display (which is where Oolite starts on) is HDR enabled and notify the user in case it is not. If no HDR display capable primary device has been found, the user has the choice to launch the game anyway or quit.
Additionally contained in this PR are the following:
- The minimum Wibndows version requirement is hereby raised to Windows 7 64-bit. This is due to the Win APIs used for HDR detection.
- The main thread's priority is now elevated to Time Critical when the game window has focus, When focus is lost, the main thread is returned to normal priority again.
- If a valid window surface could not be created at startup, …

HDR output display detection on Windows

---

.github/workflows/build-all.yml
.github/workflows/build-windows.yml

We can now build on Ubuntu again.
For changes on master a release is created, for changes on other branches a prerelease is created. 
This will allow to use the CI/CD pipeline for both releases and for development.

add Ubuntu build

---

src/Core/Universe.m

Similar to #417 and https://github.com/OoliteProject/oolite/commit/0866adf9b9a4479d045a53a1ce24157fd736afa5 this PR supplies a literal format string to avoid the `format-security` error produced by gcc.

Fix gcc -Werror=format-security

---

src/Core/GuiDisplayGen.m
src/Core/Materials/OOConcreteTexture.m
src/Core/Materials/OOTexture.h

GUI textures like backgrounds, foregrounds etc. are not processed in any way after having been loaded. However, they are subject to tone nmapping and gamma correction at the end of the render pass because they are part of the final scene texture. So we need to declare them as SRGBA textures when they are loaded so that OpenGL will automatically convert them to linear space and the subsequent tone mapping and gamma correction shader operations will not result in heavy distortion of their colors due to over-correction.
This should fix #412.

GUI background and foreground images are now treated as having SRGBA internal format

---

LICENSE

Reasoning is to have the license at the standard location where Github and others expect to find it.

Create LICENSE with content based on Doc/LICENSE.TXT

---

installers/posix/setup.body

Resolve the issue described in http://aegidian.org/bb/viewtopic.php?f=9&t=21402
A matching commit will be on branch doNotBlockOnError in the oolite-linux-dependencies repository

Ensure the startup script shows a notification on Oolite failure. 

---

GNUmakefile
src/SDL/MyOpenGLView.h
src/SDL/MyOpenGLView.m

Apps by default are set to render their windows in light mode for compatibility reasons. However, ideally they should conform to the users' preferences and the light / dark mode setting happens to be one of the most important ones due to its immediate visible effect on presentation. With this PR, the Windows personalization dark / light color mode setting is now honored by the game window.
Oolite now detects the light / dark UI mode setting and adjusts itself as required. Additionally, it listens for real-time changes of the setting and can re-adjust on the fly if the user change their preference with the game window open and running.
Example image showing dark mode:

Dark Mode Support on Windows

---

src/Core/Entities/PlayerEntity.h
src/Core/Entities/PlayerEntity.m
src/Core/Entities/PlayerEntityControls.m
src/Core/Entities/PlayerEntityLegacyScriptEngine.h
src/Core/Entities/PlayerEntityLegacyScriptEngine.m
src/Core/Entities/PlayerEntityScriptMethods.h
src/Core/Entities/PlayerEntityScriptMethods.m
src/Core/Entities/ShipEntity.m
src/Core/Scripting/OOJSMission.m

Presently, the only key a mission screen can watch for is the "enter" key, when the player presses it on a choice. This limits what can be done with UI design.
This PR aims to correct this by allowing any key (including function keys or shift/ctrl/alt combinations) to be registered on a mission screen, with the callback function being called when one is pressed. Two changes are needed for a mission screen to make use of this feature.
1. Add the "registerKeys" property to the options dictionary. This property lists all the desired keys for the mission screen in a dictionary object. For example:
```
this.$openScreen = function () {
var opts = {
screenID: "myScreenID",
title: "Sample Title",
message: "A sample screen.",
choices: {"default":{"text":"Press ESC to exit"}},
registerKeys: …
```

Adding ability to define additional keys on a mission screen

---

GNUmakefile
Oolite.xcodeproj/project.pbxproj
src/Core/Entities/PlayerEntity.h
src/Core/Entities/PlayerEntity.m
src/Core/Entities/PlayerEntityControls.m
src/Core/Scripting/OOJSGlobal.m
src/Core/Scripting/OOJSGuiScreenKeyDefinition.h
src/Core/Scripting/OOJSGuiScreenKeyDefinition.m
src/Core/Scripting/OOJSMission.m

(resubmitted because I messed up the rebase)
One of the problems that has developed over time is the confusing list of F4 Interface screens that are added by OXP's. It doesn't take long for the list to become long and unwieldy.
The problem is that the F4 page is the only place to put a mission screen page. Even if the mission page is specifically related to the market, or the chart, or the system info view, they all have to go on the F4 page with some basic grouping as the only way to arrange things.
Coupled with this is the usefulness some of the pages have beyond the station. It makes sense to be able to view chart related info, or market info, as provided by an OXP, while in flight. The message has always been "do not show mission screens in flight," but that logic is counter to the …

Adds ability to define custom keys on most gui screens

---

src/Core/OOALSoundChannel.m

This is a fix for a possible memory leak on the Mac based on the info here: [https://blog.vucica.net/2011/06/avoiding-memory-leak-in-openal-and-crash-in-openal-for-mac.html](url)
I've been running this change in my local build (Windows) for a while without impact. But it would be good to hear from others (on Linux particularly) to make sure there is no obvious issues there before merging.
It may not be a fix for the issue with sounds on Mac, but it might help.

Fix for possible memory leak on Mac

---

src/Core/Entities/PlayerEntity.h
src/Core/Entities/PlayerEntity.m
src/Core/Scripting/OOJSPlayerShip.m
src/Core/Universe.m

This PR is a QOL enhancement for witch space jumps. It adds the jump cause to all jump events, so each event can know what type of jump was performed. It also adds a new property to the player ship, "previousSystem", which holds the originating system ID from where the player has come. It will be in the range of -1 to 255.
On a programming note, I'm not happy with these lines:
`
ShipScriptEvent(context, self, "shipWillEnterWitchspace", STRING_TO_JSVAL(JS_InternString(context, [[self jumpCause] UTF8String])), INT_TO_JSVAL([w_hole destination]));
`
Something feels off with the number of conversions I'm doing to pass the jump cause to the STRING_TO_JSVAL function. If there's a better way, please let me know! Ideally I'd like to return to the "NoCx" version of "ShipScriptEvent" (and therefore …

Witchjump js enhancements

---

src/Core/Scripting/OOJSShip.m

For real, this time!
By default, the "canAwardEquipment" checks the equipment with the "scripted" context. This PR allows other contexts to be tested on an equipment item. 
For example:
`player.ship.canAwardEquipment("EQ_NAVAL_ENERGY_UNIT")` will return true. This is because, with the "scripted" context, it is allowed to be awarded to the player. However, there are restrictions on whether you can purchase the equipment or not. With this PR, you can do the following:
`player.ship.canAwardEquipment("EQ_NAVAL_ENERGY_UNIT", "purchase")`, which will return false if the player has not yet completed the mission it relates to.

Expanding ship.canAwardEquipment to allow other contexts

---

src/Core/Entities/ShipEntity.m

Currently, regardless of what a splinter might have defined, it will always be given minerals when it is spawned from mining a boulder. This patch will check for the "cargo_carried" property in shipdata, and if found, will allow it to define the makeup of the splinter. If no "cargo_carried" property is defined, the default behaviour will apply.

Splinters that have cargo_carried defined will use that on spawn

---

Doc/CHANGELOG.TXT
src/Core/Entities/PlayerEntity.h
src/Core/Entities/PlayerEntity.m
src/Core/Entities/PlayerEntityKeyMapper.h
src/Core/Entities/PlayerEntityKeyMapper.m
src/Core/OOEquipmentType.h
src/Core/OOEquipmentType.m
src/Core/Scripting/OOJSEquipmentInfo.m

With this PR, you can now set "default_activate_key" and "default_mode_key" in your equipment.plist definition. If the chosen key conflicts with another key when loading, the setting will be ignored.
The definition is the same as for other key settings, in that it is an array of dictionary items. For example:
```
default_activate_key = ({key = "0"; shift = true;});
default_mode_key = ({key = "9"; mod1 = true;});
```
If you change the default key for the equipment item, the "Overrides" column will now show that the key setting has changed from the default.

Added ability to set default activate+mode keys for equipment items

---

Doc/CHANGELOG.TXT
src/Core/Entities/PlayerEntityLegacyScriptEngine.m

This PR fixes the issue where too many choices have been defined in the options dictionary to fit on the current mission screen.
Essentially, what I'm doing here is (apart from putting a notice in the log) ignoring choices that fall outside the scope of the screen. This could potentially leave the screen in a weird state, if (say) the option to close the screen is one of the excluded options.
As an alternative, I could ignore *all* options if too many have been defined. Let me know your preference.

Fixes issue with too many choices to fit on mission screen

---

src/Core/Entities/PlayerEntityKeyMapper.m

The fail was causing an error to be written to the log, but the app continued to run. See issue #479 
The issue was only occurring in the Linux build, but I have tested this on both Windows and Linux.

Fixes issue where setting keys for custom equipment was failing

---

Doc/CHANGELOG.TXT
src/Core/NSStringOOExtensions.h
src/Core/NSStringOOExtensions.m
src/Core/OOOXZManager.m

This should fix issue #376 and reduce potential confusion.
Part of this PR are also four new NSString extensions: -stringByTrimmingLeadingCharactersInSet, -stringByTrimmingLeadingWhitespaceAndNewlineCharacters, -stringByTrimmingTrailingCharactersInSet and -stringByTrimmingTrailingWhitespaceAndNewlineCharacters: The last two are not used in this fix, but they are handy and can be useful in the future if need be.
While at it I also applied the same behavior on the remaining string filters, namely author, tag and category.

OXZ Manager: Leading whitespaces from string filters are now stripped.

---

README.md

Tested as of 20241206 under Tumbleweed version 20241111

Build instructions openSUSE

---

.github/workflows/build-all.yml
Doc/ApiDocIntro.dox

This allows not only to browse doxygen documentation for Oolite, but also see reports how much has been documented and where improvements may be useful. Hopefully someone with knowledge on the code would add information that others then may use to better understand the code.
The coverage report is available in the doxygen documentation both from the main page as well as in the topics menu.

Documentation coverage report

---

.github/workflows/build-all.yml

Fixed a chain of events:
- unzip was configured to only overwrite older or nonexisting files
- we decided to keep the old PDFs
- during checkout git would assign new timestamps
Thus the timestamp of the outdated files was later than the generated files and the files would not get overwritten.

use the generated pdfs for further builds

---

.github/workflows/build-all.yml

Fixed a chain of events:
- unzip was configured to only overwrite older or nonexisting files
- we decided to keep the old PDFs
- during checkout git would assign new timestamps
Thus the timestamp of the outdated files was later than the generated files and the files would not get overwritten.

Use generated PDFs in releases

---

README.md
src/Core/HeadUpDisplay.m
src/Core/OOPriorityQueue.m

I believe the issue is with gcc 15, possibly a compiler bug, but I didn't investigate further after finding the workaround of adding parentheses. The error looked like this + same thing with the `if (_count * 2 <= _capacity)` line:
```cpp
src/Core/HeadUpDisplay.m: In function ‘-[HeadUpDisplay renderHUD]’:
src/Core/HeadUpDisplay.m:841:13: error: unknown type name ‘_crosshairWidth’
841 |         if (_crosshairWidth * lineWidth > 0)
|             ^~~~~~~~~~~~~~~
src/Core/HeadUpDisplay.m:841:41: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘>’ token
841 |         if (_crosshairWidth * lineWidth > 0)
|                                         ^
src/Core/HeadUpDisplay.m:841:13: error: declaration in the controlling expression must have an initializer
841 |         if …
```

Added workaround for weird compiler behaviour 
